[2025-01-08T13:43:28.115+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:43:28.141+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:43:28.149+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:43:28.178+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): unpack_to_raw> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:43:28.192+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2025-01-08T13:43:28.201+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'unpack_to_raw', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpsi0i1ca4']
[2025-01-08T13:43:28.208+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask unpack_to_raw
[2025-01-08T13:43:28.244+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:43:28.317+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.unpack_to_raw scheduled__2025-01-01T00:00:00+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:43:28.527+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='unpack_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:43:28.531+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:43:28.533+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/build/unpack_to_raw.py --output-dir /opt/***/data/raw --endpoint-url http://localstack:4566']
[2025-01-08T13:43:28.554+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:43:42.953+0000] {subprocess.py:93} INFO - Téléchargement des données...
[2025-01-08T13:43:43.002+0000] {subprocess.py:93} INFO - Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]Generating test split: 100%|██████████| 4358/4358 [00:00<00:00, 103518.49 examples/s]
[2025-01-08T13:43:43.135+0000] {subprocess.py:93} INFO - Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]Generating train split:  74%|███████▎  | 27000/36718 [00:00<00:00, 256815.67 examples/s]Generating train split: 100%|██████████| 36718/36718 [00:00<00:00, 275384.77 examples/s]
[2025-01-08T13:43:45.913+0000] {subprocess.py:93} INFO - Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]Generating validation split: 100%|██████████| 3760/3760 [00:00<00:00, 335251.87 examples/s]
[2025-01-08T13:43:45.914+0000] {subprocess.py:93} INFO - Données téléchargées et organisées.
[2025-01-08T13:43:45.915+0000] {subprocess.py:93} INFO - Combinaison et téléversement des fichiers...
[2025-01-08T13:43:45.915+0000] {subprocess.py:93} INFO - Erreur lors du téléversement : Unable to locate credentials
[2025-01-08T13:43:45.916+0000] {subprocess.py:93} INFO - Traitement terminé.
[2025-01-08T13:43:46.181+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:43:46.224+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=unpack_to_raw, execution_date=20250101T000000, start_date=20250108T134328, end_date=20250108T134346
[2025-01-08T13:43:46.278+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:43:46.317+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
