[2025-01-08T13:45:10.925+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-08T13:45:10.970+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-08T13:45:10.973+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:45:11.017+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): preprocess_to_staging> on 2025-01-06 00:00:00+00:00
[2025-01-08T13:45:11.029+0000] {standard_task_runner.py:57} INFO - Started process 644 to run task
[2025-01-08T13:45:11.036+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'preprocess_to_staging', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4tadh5jk']
[2025-01-08T13:45:11.046+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask preprocess_to_staging
[2025-01-08T13:45:11.105+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:45:11.486+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-06T00:00:00+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:45:12.030+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-08T13:45:12.035+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:45:12.043+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/preprocess_to_staging.py --bucket_raw raw --db_host mysql --db_user root --db_password root --endpoint-url http://localstack:4566']
[2025-01-08T13:45:12.068+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:45:16.129+0000] {subprocess.py:93} INFO - Récupération des données depuis le bucket raw...
[2025-01-08T13:45:16.130+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données depuis S3: Unable to locate credentials
[2025-01-08T13:45:16.361+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:45:16.404+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=preprocess_to_staging, execution_date=20250106T000000, start_date=20250108T134510, end_date=20250108T134516
[2025-01-08T13:45:16.464+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:45:16.502+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
